# Generated by Django 4.0.4 on 2022-06-22 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=50)),
                ('is_email_id_verified', models.BooleanField(default=False)),
                ('contact_number', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(max_length=6)),
                ('password', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserContactListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_contact_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_contact_with', to='user_api.usermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user_api.usermodel')),
            ],
            options={
                'db_table': 'user_contact_list',
                'unique_together': {('user', 'in_contact_with')},
            },
        ),
    ]
