# Generated by Django 4.0.4 on 2022-06-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_alter_usermodel_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_pic',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='profile_pic/'),
        ),
    ]
