# Generated by Django 4.0.4 on 2022-06-22 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2000)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('msg_is_read', models.BooleanField(default=False)),
                ('msg_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_from', to='user_api.usermodel')),
                ('msg_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_to', to='user_api.usermodel')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
