# Generated by Django 4.0.4 on 2022-06-22 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wp_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30)),
                ('payment_id', models.CharField(blank=True, max_length=30, null=True)),
                ('amount', models.FloatField()),
                ('days_added', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('done_date', models.DateField(auto_now=True)),
                ('business_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wp_api.businessaccountmodel')),
            ],
            options={
                'db_table': 'payment_history',
            },
        ),
    ]
