# Generated by Django 4.0.4 on 2022-06-22 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wp_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlansModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscription_plans',
            },
        ),
        migrations.CreateModel(
            name='WpBusiAcc_Sub_plansModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wp_api.businessaccountmodel')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_plans_api.subscriptionplansmodel')),
            ],
            options={
                'db_table': 'wp_business_acc_subscription_plans',
            },
        ),
        migrations.AddField(
            model_name='subscriptionplansmodel',
            name='business_account',
            field=models.ManyToManyField(through='subscription_plans_api.WpBusiAcc_Sub_plansModel', to='wp_api.businessaccountmodel'),
        ),
    ]
